config/routes.rb
Thuli::Application.routes.draw do
  resources :wards

  resources :brands

  resources :transactions

  resources :vendors do
      collection do
        get 'login'
        post 'login_check' => 'vendors#login_check'
        get 'new_booking' => 'vendors#new_booking'
        get 'accept'
        get 'decline' 
        get 'submit_otp'
      end
  end

  resources :customers do
      collection do
        get 'new_registration'
      end
    end

  

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :addres, :name, :password, :vend_type, :ward
  has_many :transactions
  has_and_belongs_to_many :wards
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])
    @transactions = @vendor.transactions

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :no_content }
    end
  end

  def login
    @vendor = Vendor.new
  end

  def login_check
    @vend = Vendor.find{|temp| temp.name == params[:name] && temp.password == params[:password]}
    if @vend.present?
      redirect_to action: "new_booking" , id: @vend.id
    else
      redirect_to action: "index" 
    end
  end

  def new_booking
    @vendor = Vendor.find(params[:id])
    @transactions = @vendor.transactions
  end

  def accept
     @transaction = Transaction.find(params[:id])
     @transaction.cccepted = true
     @transaction.save
  end

  def decline


  end

  def submit_otp
    new_otp = params[:otp]
    transaction = Transaction.find(params[:id])
    if(transaction.otp == new_otp)
      Transaction.find(params[:id]).destroy
    end 
    redirect_to :back
  end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :addres %><br />
    <%= f.text_field :addres %>
  </div>
  <div class="field">
    <%= f.label :vend_type %><br />
    <%= f.check_box :vend_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/accept.html.erb
<h1>Accept</h1>

app/views/vendors/decline.html.erb
<h1>decline</h1>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Available bookings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Addres</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vendors.each do |vendor| %>
  <tr>
    <td><%= vendor.name %></td>
    <td><%= vendor.password %></td>
    <td><%= vendor.addres %></td>
    <td><%= vendor.vend_type %></td>
    <td><%= link_to 'Show', vendor %></td>
    <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
    <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

<% end %>
</table>

<br />

<%= link_to 'New Vendor', new_vendor_path %>
<%= link_to 'Vendor Login', action: "login" %>

app/views/vendors/login.html.erb
<h1>Vendor login</h1>

<%= form_tag "/vendors/login_check", method: 'POST' %> 
  <%= label_tag(:name, "Username") %>
  <%= text_field_tag(:name) %> 
  <br><br>
  <%= label_tag(:password, "Password") %>
  <%= text_field_tag(:password) %> 
<br><br>
<%= submit_tag("Login") %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/new_booking.html.erb
<h1>Available bookings</h1>
<% @transactions.each do |transaction|%>
<%if transaction.cccepted == nil or transaction.cccepted == false%>
<p>
  <b>Customer id:</b>
  <%= transaction.customer_id %>
</p>

<p>
  <b>Brand id:</b>
  <%= transaction.brand_id%>
</p>
<p>
  <b>Price:</b>
  <%= transaction.price*10%>
</p>
<p>
  <%= link_to 'Accept',  action: "accept", id: transaction.id %> 
  <%= link_to 'Decline',  action: "decline" %> 
 
</p>
<%= link_to 'Show ongoing',  action: "show" , id: @vendor.id %> 

<%end%>
<%end%>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>
<h1>List of transactions belonging to current Vendor</h1>
<%@transactions.each do |transaction|%>
<%if transaction.cccepted == true%>
<p>
  <b>Name:</b>
  <%= transaction.id %>
</p>

<p>
  <b> Vendor name:</b>
  <%= Vendor.find(transaction.vendor_id).name %>
</p>

<p>
  <b>Customer id:</b>
  <%= transaction.customer_id %>
</p>

<p>
  <b>Brand id:</b>
  <%= transaction.brand_id%>
</p>
<p>
  <b>Price:</b>
  <%= transaction.price%>
</p>
<p>
  <b>Ordered at:</b>
  <%= transaction.created_at%>
</p>
<p>
  <b>OTP:</b>
  <%= text_field_tag(:otp) %> 
  <%= link_to 'Submit OTP', action: "submit_otp" ,id: transaction.id %>

</p>
<%end%>
<%end%>
<%= link_to 'New Bookings',  action: "new_booking" ,id: @vendor.id%> 

<%= link_to 'Back', vendors_path %>