config/routes.rb
Thuli::Application.routes.draw do
  resources :wards

  resources :brands

  resources :transactions

  resources :vendors do
      collection do
        get 'login'
        post 'login_check' => 'vendors#login_check'
        get 'new_booking' => 'vendors#new_booking'
        get 'accept'
        get 'decline' 
        get 'submit_otp'
      end
  end

  resources :customers do
      collection do
        get 'new_registration'
      end
    end

  

end

app/models/ward.rb
class Ward < ActiveRecord::Base
  # attr_accessible :title, :body
  has_one :customer
  has_and_belongs_to_many :vendors
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  # GET /wards
  # GET /wards.json
  def index
    @wards = Ward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wards }
    end
  end

  # GET /wards/1
  # GET /wards/1.json
  def show
    @ward = Ward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ward }
    end
  end

  # GET /wards/new
  # GET /wards/new.json
  def new
    @ward = Ward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ward }
    end
  end

  # GET /wards/1/edit
  def edit
    @ward = Ward.find(params[:id])
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(params[:ward])

    respond_to do |format|
      if @ward.save
        format.html { redirect_to @ward, notice: 'Ward was successfully created.' }
        format.json { render json: @ward, status: :created, location: @ward }
      else
        format.html { render action: "new" }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wards/1
  # PUT /wards/1.json
  def update
    @ward = Ward.find(params[:id])

    respond_to do |format|
      if @ward.update_attributes(params[:ward])
        format.html { redirect_to @ward, notice: 'Ward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward = Ward.find(params[:id])
    @ward.destroy

    respond_to do |format|
      format.html { redirect_to wards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= form_for(@ward) do |f| %>
  <% if @ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
      <% @ward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<h1>Editing ward</h1>

<%= render 'form' %>

<%= link_to 'Show', @ward %> |
<%= link_to 'Back', wards_path %>

app/views/wards/index.html.erb
<h1>Listing wards</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wards.each do |ward| %>
  <tr>
    <td><%= link_to 'Show', ward %></td>
    <td><%= link_to 'Edit', edit_ward_path(ward) %></td>
    <td><%= link_to 'Destroy', ward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ward', new_ward_path %>

app/views/wards/new.html.erb
<h1>New ward</h1>

<%= render 'form' %>

<%= link_to 'Back', wards_path %>

app/views/wards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_ward_path(@ward) %> |
<%= link_to 'Back', wards_path %>